from .aluno import AlunoListSerializer, AlunoCreateSerializer, AlunoRetrieveSerializer
from .apoiador import ApoiadorListSerializer, ApoiadorRetrieveSerializer, ApoiadorCreateSerializer
from .avaliacao import AvaliacaoSerializer, AvaliacaoDetailSerializer
from .avaliador import AvaliadorListSerializer, AvaliadorSerializer
from .criterio import CriterioListSerializer, CriterioSerializer
from .curso import CursoListSerializer, CursoSerializer
from .edicao import EdicaoListSerializer, EdicaoRetrieveSerializer, EdicaoCreateSerializer, AvaliadorEdicaoDetailSerializer, AvaliadorEdicaoSerializer, EdicaoCriterioDetailSerializer, EdicaoCriterioSerializer
from .equipe import EquipeCreateSerializer, EquipeListSerializer, EquipeRetrieveSerializer
from .ranking import RankingDetailSerializer, RankingSerializer
from .turma import TurmaDetailSerializer, TurmaSerializer