# Generated by Django 5.1.3 on 2024-12-02 09:27

import uploader.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=uploader.models.image.image_file_path),
        ),
    ]
