# Generated by Django 5.1.3 on 2024-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
