from .criterio import Criterio
from .edicao import Edicao
from .edicao import AvaliadorEdicao
from .edicao import EdicaoCriterio
from .curso import Curso
from .turma import Turma
from .avaliador import Avaliador
from .equipe import Equipe
from .avaliacao import Avaliacao
from .aluno import Aluno
from .apoiador import Apoiador
from .ranking import Ranking