from .criterion import Criterion
from .edition import Edition
from .course import Course
from .class_info import ClassInfo
from .avaliator import Avaliator
from .team import Team
from .avaliation import Avaliation
from .student import Student
from .supporter import Supporter
from .ranking import Ranking
from .category import Category