# Generated by Django 5.0.4 on 2024-04-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField()),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('peso', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('sigla', models.CharField(max_length=10)),
                ('nivelCurso', models.CharField(choices=[('tecn', 'Técnico'), ('grad', 'Graduação'), ('posgrad', 'Pós-Graduação'), ('mest', 'Mestrado'), ('dout', 'Doutorado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('cursos', models.ManyToManyField(to='hackathon.curso')),
            ],
        ),
        migrations.CreateModel(
            name='edicao_criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.criterio')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.edicao')),
            ],
        ),
        migrations.CreateModel(
            name='equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('linkDeploy', models.URLField(blank=True, null=True)),
                ('linkRepositorio', models.URLField(blank=True, null=True)),
                ('linkApresentacao', models.URLField(blank=True, null=True)),
                ('linkVideo', models.URLField(blank=True, null=True)),
                ('linkPitch', models.URLField(blank=True, null=True)),
                ('alunos', models.ManyToManyField(to='hackathon.aluno')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.edicao')),
            ],
        ),
        migrations.CreateModel(
            name='avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.avaliador')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.criterio')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.curso')),
            ],
        ),
        migrations.AddField(
            model_name='edicao',
            name='turmasEnvolvidas',
            field=models.ManyToManyField(to='hackathon.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.turma'),
        ),
    ]
