# Generated by Django 5.0.4 on 2024-07-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='members_per_team',
            new_name='max_members',
        ),
        migrations.AddField(
            model_name='edition',
            name='min_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
