# Generated by Django 5.0.4 on 2024-04-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='avaliador',
            options={'ordering': ['nome'], 'verbose_name': 'Avaliador', 'verbose_name_plural': 'Avaliadores'},
        ),
        migrations.AlterModelOptions(
            name='criterio',
            options={'ordering': ['descricao'], 'verbose_name': 'Critério', 'verbose_name_plural': 'Critérios'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='edicao',
            options={'ordering': ['ano', 'semestre'], 'verbose_name': 'Edição', 'verbose_name_plural': 'Edições'},
        ),
        migrations.AlterModelOptions(
            name='edicao_criterio',
            options={'ordering': ['edicao__ano', 'edicao__semestre', 'criterio'], 'verbose_name': 'Critério da Edição', 'verbose_name_plural': 'Critérios das Edições'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['nome'], 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['nome'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.CreateModel(
            name='avaliador_edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.avaliador')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.edicao')),
            ],
            options={
                'verbose_name': 'Avaliador da Edição',
                'verbose_name_plural': 'Avaliadores das Edições',
                'ordering': ['avaliador', 'edicao__ano', 'edicao__semestre'],
            },
        ),
    ]
