# Generated by Django 5.0.4 on 2024-09-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='avaliator',
            new_name='avaliators',
        ),
        migrations.RenameField(
            model_name='edition',
            old_name='criterion',
            new_name='criteria',
        ),
    ]
