# Generated by Django 5.0.4 on 2024-09-26 17:09

import django_base64field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='file',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
