# Generated by Django 5.0.4 on 2024-10-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='involved_classes',
            field=models.ManyToManyField(to='hackathon.classinfo'),
        ),
    ]
