# Generated by Django 5.0.4 on 2024-09-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_rename_avaliator_edition_avaliators_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliation',
            old_name='note',
            new_name='grade',
        ),
    ]
