# Generated by Django 5.0.4 on 2024-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_edition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='edition_photo',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='file',
        ),
        migrations.AddField(
            model_name='edition',
            name='edition_photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
