# Generated by Django 5.0.4 on 2024-04-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_alter_aluno_options_alter_avaliador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='aceitaInscricoes',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='edicao',
            name='fotoEdicao',
            field=models.ImageField(blank=True, null=True, upload_to='edicoes'),
        ),
        migrations.AddField(
            model_name='edicao',
            name='prazoInscricoes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='dataInscricao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='fotoEquipe',
            field=models.ImageField(blank=True, null=True, upload_to='equipes'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='inscricaoValidada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='apoiadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='apoiadores')),
                ('link', models.URLField()),
                ('edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hackathon.edicao')),
            ],
            options={
                'verbose_name': 'Apoiador',
                'verbose_name_plural': 'Apoiadores',
                'ordering': ['empresa'],
            },
        ),
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaFinal', models.DecimalField(decimal_places=1, max_digits=3)),
                ('classificacao', models.IntegerField()),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.edicao')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hackathon.equipe')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['edicao__ano', 'edicao__semestre', 'equipe__nome', 'classificacao'],
            },
        ),
    ]
