# Generated by Django 5.0.4 on 2024-04-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_edicao_aceitainscricoes_edicao_fotoedicao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
