# Generated by Django 5.0.4 on 2024-10-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_team_leader_alter_team_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
