# Generated by Django 5.0.4 on 2024-04-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_avaliacao_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apoiadores',
            new_name='Apoiador',
        ),
    ]
