# Generated by Django 5.0.4 on 2024-10-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='final_grade',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
