# Generated by Django 5.0.4 on 2024-04-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_rename_apoiadores_apoiador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nivelCurso',
            new_name='nivel_curso',
        ),
        migrations.RenameField(
            model_name='edicao',
            old_name='aceitaInscricoes',
            new_name='aceita_inscricoes',
        ),
        migrations.RenameField(
            model_name='edicao',
            old_name='fotoEdicao',
            new_name='foto_edicao',
        ),
        migrations.RenameField(
            model_name='edicao',
            old_name='prazoInscricoes',
            new_name='prazo_inscricoes',
        ),
        migrations.RenameField(
            model_name='edicao',
            old_name='turmasEnvolvidas',
            new_name='turmas_envolvidas',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='dataInscricao',
            new_name='data_inscricao',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='fotoEquipe',
            new_name='foto_equipe',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='inscricaoValidada',
            new_name='inscricao_validada',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='linkApresentacao',
            new_name='link_apresentacao',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='linkDeploy',
            new_name='link_deploy',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='linkPitch',
            new_name='link_pitch',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='linkRepositorio',
            new_name='link_repositorio',
        ),
        migrations.RenameField(
            model_name='equipe',
            old_name='linkVideo',
            new_name='link_video',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='notaFinal',
            new_name='nota_final',
        ),
    ]
