# Generated by Django 5.0.4 on 2024-09-27 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_alter_images_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='edition_photo_base64',
        ),
        migrations.AddField(
            model_name='edition',
            name='photo_base64_edition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.images'),
        ),
    ]
