# Generated by Django 5.0.4 on 2024-10-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_alter_avaliation_grade_alter_ranking_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliation',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='final_grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
