# Generated by Django 5.0.4 on 2024-09-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_remove_edition_edition_photo_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
