# Generated by Django 5.0.4 on 2024-04-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_rename_nivelcurso_curso_nivel_curso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='avaliador_edicao',
            new_name='AvaliadorEdicao',
        ),
        migrations.RenameModel(
            old_name='edicao_criterio',
            new_name='EdicaoCriterio',
        ),
    ]
