# Generated by Django 5.0.4 on 2024-10-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_team_project_name_alter_avaliation_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
        migrations.RemoveField(
            model_name='team',
            name='deploy_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pitch_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='presentation_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='repository_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='valid_registration',
        ),
        migrations.RemoveField(
            model_name='team',
            name='video_link',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('deploy_link', models.URLField(blank=True, null=True)),
                ('repository_link', models.URLField(blank=True, null=True)),
                ('presentation_link', models.URLField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('pitch_link', models.URLField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True, null=True)),
                ('valid_registration', models.BooleanField(blank=True, default=False, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hackathon.category')),
                ('project_photo_base64', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.images')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hackathon.project'),
        ),
    ]
