# Generated by Django 5.0.4 on 2024-04-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_rename_avaliador_edicao_avaliadoredicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edicao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edicao',
            name='quantidade_membros_equipe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lider', to='hackathon.aluno'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, related_name='alunos', to='hackathon.aluno'),
        ),
    ]
