# Generated by Django 5.0.4 on 2024-09-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_team_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='desc',
        ),
        migrations.AddField(
            model_name='team',
            name='photo_base64_edition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.images'),
        ),
    ]
