# Generated by Django 5.0.4 on 2024-10-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_remove_team_category_remove_team_deploy_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
    ]
