# Generated by Django 5.0.4 on 2024-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_rename_project_name_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='valid_registration',
        ),
        migrations.AddField(
            model_name='team',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='valid_registration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
