# Generated by Django 5.0.4 on 2024-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_edicao_data_fim_edicao_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='alunos',
            field=models.ManyToManyField(related_name='alunos', to='hackathon.aluno'),
        ),
    ]
