# Generated by Django 5.0.4 on 2024-09-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_remove_team_desc_team_photo_base64_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='photo_team',
        ),
    ]
