# Generated by Django 5.0.4 on 2024-10-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_remove_project_valid_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='registration_date',
        ),
    ]
