# Generated by Django 5.0.4 on 2024-09-29 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_remove_team_photo_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='photo_base64_edition',
            new_name='photo_base64_team',
        ),
    ]
