# Generated by Django 5.0.4 on 2024-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_alter_equipe_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edicaocriterio',
            name='criterio',
        ),
        migrations.RemoveField(
            model_name='edicaocriterio',
            name='edicao',
        ),
        migrations.AddField(
            model_name='edicao',
            name='avaliador',
            field=models.ManyToManyField(to='hackathon.avaliador'),
        ),
        migrations.AddField(
            model_name='edicao',
            name='criterio',
            field=models.ManyToManyField(to='hackathon.criterio'),
        ),
        migrations.DeleteModel(
            name='AvaliadorEdicao',
        ),
        migrations.DeleteModel(
            name='EdicaoCriterio',
        ),
    ]
