# Generated by Django 5.0.4 on 2024-10-25 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_remove_project_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='photo_base64_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.images'),
        ),
    ]
