# Generated by Django 5.0.4 on 2024-10-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_alter_edition_photo_base64_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo_base64_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.images'),
        ),
    ]
