# Generated by Django 5.0.4 on 2024-11-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_remove_team_project_project_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo_base64',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.images'),
        ),
    ]
