# Generated by Django 5.0.4 on 2024-11-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0014_alter_project_project_photo_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
