# Generated by Django 5.1.3 on 2024-12-01 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0015_project_description_alter_criterion_weight'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='photo_base64_edition',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_photo_base64',
        ),
        migrations.RemoveField(
            model_name='team',
            name='photo_base64_team',
        ),
        migrations.AddField(
            model_name='edition',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
