# Generated by Django 5.1.3 on 2024-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0016_remove_edition_photo_base64_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='hackathon.category'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='supporters',
            field=models.ManyToManyField(blank=True, null=True, to='hackathon.supporter'),
        ),
    ]
