# Generated by Django 5.1.3 on 2024-12-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_alter_edition_categories_alter_edition_supporters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
