# Generated by Django 5.1.3 on 2024-12-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0018_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='categories',
            field=models.ManyToManyField(to='hackathon.category'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='supporters',
            field=models.ManyToManyField(to='hackathon.supporter'),
        ),
    ]
