teams = [
    {
        "name": "Time 1",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 2",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 3",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 4",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 5",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 6",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 7",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 8",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 9",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 10",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 11",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 12",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 13",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 14",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
    {
        "name": "Time 15",
        "deploy_link": "https://deploy.com",
        "repository_link": "https://repository.com",
        "presentation_link": "https://presentation.com",
        "video_link": "https://video.com",
        "pitch_link": "https://pitch.com",
        "registration_date": "2025-01-15",
        "valid_registration": False,
        "photo_team": "teams/photo_team.jpg",
    },
]