editions = [
    {
        "year": 2024,
        "semester": 1,
        "applications_accepted": True,
        "registration_deadline": "2024-07-01",
        "start_date": "2024-07-15",
        "finish_date": "2024-12-15",
        "min_members": 1,
        "max_members": 5,
    },
    {
        "year": 2024,
        "semester": 2,
        "applications_accepted": True,
        "registration_deadline": "2024-12-01",
        "start_date": "2025-01-15",
        "finish_date": "2025-06-15",
        "min_members": 1,
        "max_members": 5,
    },
    {
        "year": 2025,
        "semester": 1,
        "applications_accepted": True,
        "registration_deadline": "2025-07-01",
        "start_date": "2025-07-15",
        "finish_date": "2025-12-15",
        "min_members": 1,
        "max_members": 5,
    },
    {
        "year": 2025,
        "semester": 2,
        "applications_accepted": True,
        "registration_deadline": "2025-12-01",
        "start_date": "2026-01-15",
        "finish_date": "2026-06-15",
        "min_members": 1,
        "max_members": 5,
    },
    {
        "year": 2026,
        "semester": 1,
        "applications_accepted": True,
        "registration_deadline": "2026-07-01",
        "start_date": "2026-07-15",
        "finish_date": "2026-12-15",
        "min_members": 1,
        "max_members": 5,
    },
    {
        "year": 2026,
        "semester": 2,
        "applications_accepted": True,
        "registration_deadline": "2026-12-01",
        "start_date": "2027-01-15",
        "finish_date": "2027-06-15",
        "min_members": 1,
        "max_members": 5,
    },
    {
        "year": 2027,
        "semester": 1,
        "applications_accepted": True,
        "registration_deadline": "2027-07-01",
        "start_date": "2027-07-15",
        "finish_date": "2027-12-15",
        "min_members": 1,
        "max_members": 5,
    },
    {
        "year": 2027,
        "semester": 2,
        "applications_accepted": True,
        "registration_deadline": "2027-12-01",
        "start_date": "2028-01-15",
        "finish_date": "2028-06-15",
        "min_members": 1,
        "max_members": 5,
    },
]

criteria = [
    {
        "description": "Inovação",
        "weight": 0.2,
    },
    {
        "description": "Usabilidade",
        "weight": 0.2,
    },
    {
        "description": "Escalabilidade",
        "weight": 0.2,
    },
    {
        "description": "Manutenibilidade",
        "weight": 0.2,
    },
    {
        "description": "Documentação",
        "weight": 0.1,
    },
    {
        "description": "Apresentação",
        "weight": 0.1,
    },
]