from .student.available_student import AvailableStudentViewSet
from .supporter import SupporterViewSet
from .avaliation import AvaliationViewSet
from .criterion import CriterionViewSet
from .course import CourseViewSet
from .edition import EditionViewSet
from .team.team import TeamViewSet
from .team.accept_team import approve_team
from .team.reject_team import reject_team
from .ranking import RankingViewSet
from .class_info import ClassInfoViewSet
from .category import CategoryViewSet
from .images import ImagesViewSet