from .student import StudentViewSet
from .supporter import SupporterViewSet
from .avaliation import FreeAvaliationViewSet
from .avaliator import AvaliatorViewSet
from .criterion import CriterionViewSet
from .course import CourseViewSet
from .edition import EditionViewSet
from .team import TeamViewSet
from .ranking import RankingViewSet
from .classInfo import ClassInfoViewSet