# Generated by Django 5.0.4 on 2024-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_avaliator',
            field=models.BooleanField(default=False),
        ),
    ]
