# Generated by Django 5.0.4 on 2024-10-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_studentprofile_class_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
