# Generated by Django 5.1.3 on 2024-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_studentprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password Reset Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Password Reset Token Created'),
        ),
    ]
