avaliators = [
    {
        "name": "Avaliador 1",
        "email": "herobrineminecanal@gmail.com",
        "whatsapp": "999999999",
        "portfolio": "https://portfolio.com",
        "github": "https://github.com",
        "linkedin": "https://linkedin.com",
        "instagram": "https://instagram.com",
        "password": "123456",
    },
    {
        "name": "Avaliador 2",
        "email": "avaliador2@example.com",
        "whatsapp": "999999999",
        "portfolio": "https://portfolio.com",
        "github": "https://github.com",
        "linkedin": "https://linkedin.com",
        "instagram": "https://instagram.com",
        "password": "123456",
    },
    {
        "name": "Avaliador 3",
        "email": "avaliador3@example.com",
        "whatsapp": "999999999",
        "portfolio": "https://portfolio.com",
        "github": "https://github.com",
        "linkedin": "https://linkedin.com",
        "instagram": "https://instagram.com",
        "password": "123456",
    },
    {
        "name": "Avaliador 4",
        "email": "avaliador4@example.com",
        "whatsapp": "999999999",
        "portfolio": "https://portfolio.com",
        "github": "https://github.com",
        "linkedin": "https://linkedin.com",
        "instagram": "https://instagram.com",
        "password": "123456",
    },
    {
        "name": "Avaliador 5",
        "email": "avaliador5@example.com",
        "whatsapp": "999999999",
        "portfolio": "https://portfolio.com",
        "github": "https://github.com",
        "linkedin": "https://linkedin.com",
        "instagram": "https://instagram.com",
        "password": "123456",
    },
]

students = [
    {
        "name": "Aluno 1",
        "email": "vnhiansdt@gmail.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000001",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 2",
        "email": "aluno2@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000002",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 3",
        "email": "aluno3@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000003",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 4",
        "email": "aluno4@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000004",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 5",
        "email": "aluno5@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000005",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 6",
        "email": "aluno6@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000006",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 7",
        "email": "aluno7@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000007",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 8",
        "email": "aluno8@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000008",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 9",
        "email": "aluno9@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000009",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 10",
        "email": "aluno10@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000010",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 11",
        "email": "aluno11@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000011",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 12",
        "email": "aluno12@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000012",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 13",
        "email": "aluno13@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000013",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 14",
        "email": "aluno14@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000014",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 15",
        "email": "aluno15@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000015",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 16",
        "email": "aluno16@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000016",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 17",
        "email": "aluno17@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000017",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 18",
        "email": "aluno18@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000018",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 19",
        "email": "aluno19@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000019",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 20",
        "email": "aluno20@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000020",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 21",
        "email": "aluno21@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000021",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 22",
        "email": "aluno22@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000022",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 23",
        "email": "aluno23@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000023",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 24",
        "email": "aluno24@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000024",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 25",
        "email": "aluno25@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000025",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
    {
        "name": "Aluno 26",
        "email": "aluno26@example.com",
        "password": "student123",
        "student_profile": {
            "registration": "2021000026",
            "whatsapp": "999999999",
            "github": "https://github.com",
            "portfolio": "https://portfolio.com",
            "linkedin": "https://linkedin.com",
            "instagram": "https://instagram.com",
            "class_info": "",
        },
    },
]

teachers = [
    {"name": "Teacher 1", "email": "vinijao123690@gmail.com", "password": "teacher123"},
    {"name": "Teacher 2", "email": "teacher2@example.com", "password": "teacher456"},
    {"name": "Teacher 3", "email": "teacher3@example.com", "password": "teacher789"},
    {"name": "Teacher 4", "email": "teacher4@example.com", "password": "teacher1011"},
    {"name": "Teacher 5", "email": "teacher5@example.com", "password": "teacher1213"},
    {"name": "Teacher 6", "email": "teacher6@example.com", "password": "teacher1415"},
    {"name": "Teacher 7", "email": "teacher7@example.com", "password": "teacher1617"},
    {"name": "Teacher 8", "email": "teacher8@example.com", "password": "teacher1819"},
    {"name": "Teacher 9", "email": "teacher9@example.com", "password": "teacher2021"},
    {"name": "Teacher 10", "email": "teacher10@example.com", "password": "teacher2223"},
]
